In [2]:
import numpy as np
import math
from tabulate import tabulate

import chipsplitting as cs

from chipsplitting import pairing_matrix, PascalForm, LinearForm
from chipsplitting.hyperfield import HyperfieldVector as HV, HyperfieldHomogeneousLinearSystem as HLinSystem, grid_iter

In [17]:
def absolute(d, c):
    if c == 'd-1':
        return d-1
    if c == 'd-2':
        return d-2
    if c == 'd-3':
        return d-3
    if c == 'd-4':
        return d-4
    if c == 'd-0':
        return d
    return c

def rel(d, contraction_size, index):
    assert index < contraction_size or index > d - contraction_size
    return f"d-{d - index}" if index > contraction_size else index
    
def sign(x):
    return np.sign(x)
    
def is_contractable(p, contraction_size = 5):
    assert p.degree >= contraction_size * 3 - 1

    # check b
    for row in range(contraction_size):
        for col in range(contraction_size, p.degree - contraction_size - row + 1):
            if sign(p.support_pos[cs.utils.get_array_index(col, row)]) != sign(p.support_pos[cs.utils.get_array_index(contraction_size, row)]):
                return False

            if sign(p.support_neg[cs.utils.get_array_index(col, row)]) != sign(p.support_neg[cs.utils.get_array_index(contraction_size, row)]):
                return False

    # check c
    for col in range(contraction_size):
        for row in range(contraction_size, p.degree - contraction_size - col + 1):
            if sign(p.support_pos[cs.utils.get_array_index(col, row)]) != sign(p.support_pos[cs.utils.get_array_index(col, contraction_size)]):
                return False

            if sign(p.support_neg[cs.utils.get_array_index(col, row)]) != sign(p.support_neg[cs.utils.get_array_index(col, contraction_size)]):
                return False

    # check d1
    for j in range(contraction_size):
        for i in range(contraction_size, p.degree - j - contraction_size + 1, 2):
            if sign(p.support_pos[cs.utils.get_array_index(i, p.degree - i - j)]) != sign(p.support_pos[cs.utils.get_array_index(contraction_size, p.degree - j - contraction_size)]):
                return False
                
            if sign(p.support_neg[cs.utils.get_array_index(i, p.degree - i - j)]) != sign(p.support_neg[cs.utils.get_array_index(contraction_size, p.degree - j - contraction_size)]):
                return False

    # check d2
    for j in range(contraction_size):
        for i in range(contraction_size + 1, p.degree - j - contraction_size + 1, 2):
            if sign(p.support_pos[cs.utils.get_array_index(i, p.degree - i - j)]) != sign(p.support_pos[cs.utils.get_array_index(contraction_size + 1, p.degree - j - contraction_size - 1)]):
                return False
            if sign(p.support_neg[cs.utils.get_array_index(i, p.degree - i - j)]) != sign(p.support_neg[cs.utils.get_array_index(contraction_size + 1, p.degree - j - contraction_size - 1)]):
                return False

    return True

### Lemma 6.21 a,b,c

Goal: Find the number of valid configurations $s \in H^{V_d}$ with $|\mathrm{supp}^+(s)| = 4$ such that all basis systems $\varphi, \psi, \bar \psi$ vanish at $s$.

**Ad-hoc computation**: For the cases $d=6,...,11$ we compute possible supports for valid outcomes.

In [3]:
%%time
base_types = ["diag", "row", "col"]
support_size = 4
for d in range(6,12):
    A = [PascalForm(d, mode, unit).to_hyperfield() for mode in base_types for unit in range(d + 1)]
    linear_system = HLinSystem(A)
    solutions = []
    solutions = linear_system.quick_solve_loop(support_size)
    print(f"Number of configurations for degree={d}: {len(solutions)}")
    if solutions:
        print(f"Solutions are {[[cs.utils.to_coordinate(index) for index in sol] for sol in solutions]}")
        print()
print()

Number of configurations for degree=6: 5
Solutions are [[(3, 0), (1, 4), (0, 6), (5, 1)], [(0, 3), (4, 1), (1, 5), (6, 0)], [(1, 1), (0, 6), (3, 3), (6, 0)], [(1, 1), (0, 5), (3, 3), (6, 0)], [(1, 1), (5, 0), (0, 6), (3, 3)]]

Number of configurations for degree=7: 3
Solutions are [[(3, 1), (1, 5), (0, 7), (7, 0)], [(1, 3), (5, 1), (0, 7), (7, 0)], [(1, 1), (3, 3), (0, 7), (7, 0)]]

Number of configurations for degree=8: 0
Number of configurations for degree=9: 0
Number of configurations for degree=10: 0
Number of configurations for degree=11: 0

CPU times: user 68.3 ms, sys: 6.72 ms, total: 75 ms
Wall time: 23 ms



__Conclusion__: We conclude that only configurations $s$ of degree $d = 6$ or $d = 7$ belong to $\Omega_d$.

### Lemma 6.21 d

**Computation**: For the cases $d \geq 11$ we compute possible supports for valid outcomes.

**Contraction**:
Fix some degree $d$.
We define $\hat \varphi_i, i=1,2,3$ to be the linear form of $\varphi_{i, d - i}$ in $H[x,y,z,b,c,d,e]$. A configuration $s$ in $H^{\Xi}$ uses the following coordinates $s = [ s_{i} ]_{i=0,...,59} = [x_0,...,x_{15}, y_{16},...,y_{31},z_{32},...,z_{47}, b_{48}, ..., b_{51}, c_{52},..., c_{55}, d_{56}, ..., d_{59}, e_{60},...,e_{63}] \in H^{64}$.

#### Find valid configurations for $d \geq 12$

Fix some degree $d$. We define the following sets of Pascal equations 
$$
    A = \{ \psi_1,..., \psi_6, \varphi_1, ...,  \varphi_6 \}
$$
where $\psi_1, \psi_2, \psi_3$ are the Pascal equations respectively defined by 
```
0                0                0
* .              * .              * .
0 . .            0 . .            1 . .
0 . . .          1 . . .          0 . . .
1 . . . .        0 . . . .        0 . . . .
0 . . . . .      0 . . . . .      0 . . . . .       * stands for arbitrarily many 0
```
$\psi_4, \psi_5, \psi_6$ are the Pascal equations respectively defined by 
```
.                .                .
. .              . .              . .
. . .            . . .            . . .
. . . .          . . . .          . . . .
. . . . .        . . . . .        . . . . . 
0 1 0 0 * 0      0 0 1 0 * 0      0 0 0 1 * 0       * stands for arbitrarily many 0
```
$\varphi_1,...,\varphi_6$ are the Pascal equations respectively defined by
```
0                0                0
. 1              . 0              . 0
. . 0            . . 1            . . 0
. . . 0          . . . 0          . . . 1
. . . . *        . . . . *        . . . . *
. . . . . 0      . . . . . 0      . . . . . 0      

0                0                0
. *              . *              . *
. . 1            . . 0            . . 0
. . . 0          . . . 1          . . . 0
. . . . 0        . . . . 0        . . . . 1
. . . . . 0      . . . . . 0      . . . . . 0       * stands for arbitrarily many 0
```
and $\xi_1,...,\xi_8$ are the Pascal equations respectively defined by
```
1                 0                0                0
0 .               1 .              0 .              0 .
0 . .             0 . .            1 . .            0 . .
0 . . .           0 . . .          0 . . .          1 . . .
* . . . .         * . . . .        * . . . .        * . . . . 
0 . . . . .       0 . . . . .      0 . . . . .      0 . . . . .      

.                .                .                .
. .              . .              . .              . .
. . .            . . .            . . .            . . .
. . . .          . . . .          . . . .          . . . .
. . . . .        . . . . .        . . . . .        . . . . . 
0 * 0 0 0 1      0 * 0 0 1 0      0 * 0 1 0 0      0 * 1 0 0 0       * stands for arbitrarily many 0
```

In [3]:
def countValidConfigsForContractions(degree="even"):
    assert degree == "even" or degree == "odd", "degree must be 'even' or 'odd'"

    pos_support_size = 4
    contraction_size = 4
    d = contraction_size * 3 - 1 + (1 if degree == "even" else 2)
    base_types = ["diag", "row", "col"]
    A = [PascalForm(d, b, k) for b in base_types for k in range(contraction_size)] + [PascalForm(d, b, k) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
    A = [p.to_hyperfield().contract(contraction_size) for p in A]  
    linear_system = HLinSystem(A)
    solutions = linear_system.quick_solve_loop(pos_support_size)
    
    return solutions


In [4]:
%%time
res1 = countValidConfigsForContractions("even")
print(f"Number of configurations for even d: {len(res1)}")

res2 = countValidConfigsForContractions("odd")
print(f"Number of configurations for odd d: {len(res2)}")

Number of configurations for even d: 0
Number of configurations for odd d: 0
CPU times: user 12.6 ms, sys: 1.29 ms, total: 13.9 ms
Wall time: 12.8 ms


**Conclusion:** For $d \geq 12$ there are no valid configurations in $H^{64}$ that satisfy all Pascal equations in $A \cup \mathrm{EVEN}$ or $A \cup \mathrm{ODD}$.

**Why is this good?** It is a necessary condition for valid configurations $w \in \mathbb Z^{V_d}$ that all Pascal equations vanish at $\mathrm{sign}(w)$. Since $A \cup \mathrm{EVEN}$ is a subset of all Pascal equations and $A \cup \mathrm{EVEN}$ have no zeros for configurations $s$ with support size $\leq 4$, no valid $w \in \mathbb Z^{V_{d}}$ exist for $d \geq 12$.

In [174]:
# SOME TEST CODE
def countValidConfigsForContractions(degree="even"):
    assert degree == "even" or degree == "odd", "degree must be 'even' or 'odd'"

    pos_support_size = 5
    contraction_size = 4
    d = contraction_size * 3 - 1 + (1 if degree == "even" else 2)
    base_types = ["diag", "row", "col"]
    A = [PascalForm(d, b, k) for b in base_types for k in range(contraction_size)] + [PascalForm(d, b, k) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
    # A = A + [p - q for p in A for q in [PascalForm(d, 'diag', k) for k in range(d + 1)]]
    A = A + [PascalForm(d, 'diag', i) - PascalForm(d, 'diag', j) for i,j in [(0,1), (0,2), (0,3), (0,d-1), (0,d-2), (0,d-3), (1,2), (1, d), (1,d-2), (1,d-3), (2,d), (2,d-1), (2,d-3), (3,d), (3,d-1), (3,d-2)]]
    #A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'diag', j) for i,j in [(0,1), (0,2), (0,3), (0,d-1), (0,d-2), (0,d-3)]]
    #A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'diag', j) for i,j in [(1,2), (1,3), (1,d), (1,d-1), (1,d-2), (1,d-3)]]
    #A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'diag', j) for i,j in [(2,0), (2,d), (2,d-1), (2,d-2), (2,d-3)]]
    #A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'diag', j) for i,j in [(3,d), (3,d-1), (3,d-2), (3,d-3)]]
    A = A + [PascalForm(d, 'diag', i) - PascalForm(d, 'diag', j) for i,j in [(d-3,d), (d-2,d), (d-2,d-1), (d-1,d-2), (d-1,d)]]
    #A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'diag', j) for i,j in [(d-3,d-3), (d-3,d-2), (d-3,d-1), (d-3,d), (d-2, 0)]]
    # A = A + [PascalForm(d, 'col', i) - PascalForm(d, 'diag', j) for i,j in [(d-3, i) for i in range(d+1)]]
    # A = A + [PascalForm(d, 'row', i) - PascalForm(d, 'row', j) for i,j in [(0,i) for i in range(4)]]
    # A = A + [PascalForm(d, 'col', i) - PascalForm(d, 'row', j) for i,j in [(3,i) for i in range(4)]]
    A = [p.to_hyperfield().contract(contraction_size) for p in A if p != LinearForm.zero(d)]  
    linear_system = HLinSystem(A)
    solutions = linear_system.quick_solve_loop(pos_support_size)
    
    return solutions


In [175]:
%%time
res1 = countValidConfigsForContractions("even")
print(f"Number of configurations for even d: {len(res1)}")

res2 = countValidConfigsForContractions("odd")
print(f"Number of configurations for odd d: {len(res2)}")

Number of configurations for even d: 778
Number of configurations for odd d: 680
CPU times: user 85.3 ms, sys: 6.87 ms, total: 92.1 ms
Wall time: 86.5 ms


In [11]:
print(PascalForm(16, 'diag', 2))

   . 
   .    . 
   1    1    1 
   3    2    1    . 
   6    3    1    .    . 
  10    4    1    .    .    . 
  15    5    1    .    .    .    . 
  21    6    1    .    .    .    .    . 
  28    7    1    .    .    .    .    .    . 
  36    8    1    .    .    .    .    .    .    . 
  45    9    1    .    .    .    .    .    .    .    . 
  55   10    1    .    .    .    .    .    .    .    .    . 
  66   11    1    .    .    .    .    .    .    .    .    .    . 
  78   12    1    .    .    .    .    .    .    .    .    .    .    . 
  91   13    1    .    .    .    .    .    .    .    .    .    .    .    . 
 105   14    1    .    .    .    .    .    .    .    .    .    .    .    .    . 
 120   15    1    .    .    .    .    .    .    .    .    .    .    .    .    .    . 



In [18]:
contraction_size = 4
d = contraction_size * 3 - 1 + 3
base_types = ["row"]
A = [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(contraction_size)] + [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
A = [(d,b,k,p - q,k2) for d,b,k,p in A for k2,q in [(k,PascalForm(d, 'row', k)) for k in range(d + 1)]]
for d,b,k,p,k2 in A:
    #if not p.support_pos[0] and not p.support_neg[0]:
    if is_contractable(p, contraction_size):
        print(f"Pascal(d={d}, {b}, {k}) - Pascal(d={d}, diag, {k2})")
        #print(p)

Pascal(d=12, row, 0) - Pascal(d=12, diag, 0)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 1)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 2)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 3)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 9)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 10)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 11)
Pascal(d=12, row, 0) - Pascal(d=12, diag, 12)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 0)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 1)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 2)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 9)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 10)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 11)
Pascal(d=12, row, 1) - Pascal(d=12, diag, 12)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 0)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 1)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 2)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 3)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 9)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 10)
Pascal(d=12, row, 2) - Pascal(d=12, diag, 11)
Pa

In [19]:
contraction_size = 4
d = contraction_size * 3 - 1 + 5
base_types = ["row"]
A = [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(contraction_size)] + [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
A = [(d,b,k,p - q,k2) for d,b,k,p in A for k2,q in [(k,PascalForm(d, 'diag', k)) for k in range(d + 1)]]
for d,b,k,p,k2 in A:
    print(f"Pascal(d={d}, {b}, {k}) - Pascal(d={d}, diag, {k2})")
    print(p)

Pascal(d=16, row, 0) - Pascal(d=16, diag, 0)
   . 
   .    . 
   .    .    . 
   .    .    .    . 
   .    .    .    .    . 
   .    .    .    .    .    . 
   .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    .    .    .    . 

Pascal(d=16, row, 0) - Pascal(d=16, diag, 1)
   1 
   .   -1 
  -1   -1    . 
  -2   -1    .    . 
  -3   -1    .    .    . 
  -4   -1    .    .    .    . 
  -5   -1    .  

In [18]:
contraction_size = 4
d = contraction_size * 3 - 1 + 1
base_types = ["diag", "row", "col"]
A = [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(contraction_size)] + [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
A = [(d,b,k,p - q,k2) for d,b,k,p in A for k2,q in [(k,PascalForm(d, 'diag', k)) for k in range(4)]]
A = [(d,b,k,p + q + r,k2,k3,k4) for d,b,k,p,k2 in A for k3,q in [(k,PascalForm(d, 'row', k)) for k in range(d + 1)] for k4,r in [(k,PascalForm(d, 'col', k)) for k in range(d + 1)]]
for d,b,k,p,k2,k3,k4 in A:
    if not p.support_pos[0] and not p.support_neg[0] and not p.support_neg[4] and not p.support_pos[4] and p.support_pos[cs.utils.get_array_index(12,0)] and p.support_pos[cs.utils.get_array_index(0,12)]:
        print(f"Pascal(d={d}, {b}, {k}) - Pascal(d={d}, diag, {k2}) + Pascal(d={d}, row, {k3}) + Pascal(d={d}, col, {k4})")
        print(p.to_hyperfield())

Pascal(d=12, diag, 0) - Pascal(d=12, diag, 0) + Pascal(d=12, row, 4) + Pascal(d=12, col, 4)
   + 
   +    - 
   +    -    + 
   +    -    +    - 
   +    -    +    -    + 
   +    -    +    -    +    . 
   +    -    +    -    +    .    . 
   +    -    +    -    +    .    .    . 
   +    -    +    -    +    +    +    +    + 
   .    -    +    -    -    -    -    -    -    - 
   .    .    +    +    +    +    +    +    +    +    + 
   .    .    .    -    -    -    -    -    -    -    -    - 
   .    .    .    .    +    +    +    +    +    +    +    +    + 

Pascal(d=12, diag, 0) - Pascal(d=12, diag, 0) + Pascal(d=12, row, 4) + Pascal(d=12, col, 6)
   + 
   +    - 
   +    -    + 
   +    -    +    - 
   +    -    +    -    + 
   +    -    +    -    +    . 
   +    -    +    -    +    +    + 
   +    -    +    -    -    -    -    - 
   +    -    +    -    +    +    +    +    + 
   .    -    +    -    -    -    -    -    -    - 
   .    .    +    -    +    +    +    +    +    +    + 
   .  

In [21]:
contraction_size = 5
d = contraction_size * 3 - 1 + 1
base_types = ["diag", "row", "col"]
A = [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(contraction_size)] + [(d,b,k,PascalForm(d, b, k)) for b in base_types for k in range(d - contraction_size + 1, d + 1)]
A = [(d,b,k,p - q,k2) for d,b,k,p in A for k2,q in [(k,PascalForm(d, 'diag', k)) for k in range(d + 1)]]
for d,b,k,p,k2 in A:
    print(f"Pascal(d={d}, {b}, {k}) - Pascal(d={d}, diag, {k2})")
    print(p.to_hyperfield())

Pascal(d=15, diag, 0) - Pascal(d=15, diag, 0)
   . 
   .    . 
   .    .    . 
   .    .    .    . 
   .    .    .    .    . 
   .    .    .    .    .    . 
   .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    .    . 
   .    .    .    .    .    .    .    .    .    .    .    .    .    .    .    . 

Pascal(d=15, diag, 0) - Pascal(d=15, diag, 1)
   + 
   .    - 
   -    -    . 
   -    -    .    . 
   -    -    .    .    . 
   -    -    .    .    .    . 
   -    -    .    .    .    .    . 
   -    -    .    .    .    .    .    . 
   -    -    .    .    

**contracted & non-trivial (0 in supp)**
```
d0 - d1
d0 - d2
d0 - d3
d0 - d-1
d0 - d-2
d0 - d-3

d1 - d2
d1 - d
d1 - d-2
d1 - d-3

d2 - d
d2 - d-1
d2 - d-3

d3 - d-1
d3 - d-2
d3 - d

r0 - d1
r0 - d2
r0 - d3
r0 - d-3
r0 - d-2
r0 - d-1

r1 - d2
r1 - d3
r1 - d
r1 - d-1
r1 - d-2
r1 - d-3

r2 - d0
r2 - d
r2 - d-1
r2 - d-2
r2 - d-3

d-3 - d12
```

**contracted (no 0 in supp)**
```
d0 - d-0
```

## Theorem 6.20

With Lemma 6.21 a,b,c,d we see that valid configurations $s \in H^{V_d}$ with support size $4$ do not exist for degree $d \geq 8$. The next step is to show that for $d = 6$ and $d = 7$, the valid configurations $s \in H^{V_d}$ do not correspond to valid configurations $w \in \mathbb Z^{V_d}$. Thus, after showing this we can conclude that $|\mathrm{supp}^+(w)| = 4 \implies \mathrm{deg}(w) \leq 5$.

**Step 1.**
For degree $6$ we computed the following valid configurations in the hyperfield. We need to check if they are valid outcomes in $\mathbb Z^{V_6}$.

```
[array([-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1,  1,  0,  0,  1,  0,  0,  0]),
 array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,
         0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0]),
 array([-1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  1]),
 array([-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1]),
 array([-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  1])]
```

In [24]:
degree = 6
configurations = [
    [-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1,  1,  0,  0,  1,  0,  0,  0],
    [-1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,
         0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0],
    [-1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  1],
    [-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1],
    [-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  1]
]

for row in configurations:
    support = [toIndex(i) for i, x in enumerate(row) if x == 1 or x == -1]
    basis = list(range(len(support)))
    P = pairing_matrix(degree, basis, support)
    print(f"Pairing matrix (support={support}, basis={basis}) has determinant: {np.linalg.det(P)}")

Pairing matrix (support=[(0, 0), (1, 1), (5, 0), (0, 6), (3, 3)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (3, 0), (1, 4), (0, 6), (5, 1)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (0, 3), (4, 1), (1, 5), (6, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (1, 1), (0, 5), (3, 3), (6, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (1, 1), (0, 6), (3, 3), (6, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0


**Conclusion:** By the intervertibility criterion only the initial configuration $\mathbf 0 \in \mathbb Z^{V_d}$ can live in the support given above. Thus, no outcome of degree $6$ with support size $4$ exist.

**Step 2.** For degree $7$ we have the following support set that we need to check
```
[array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  1]),
 array([-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  1]),
 array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,
         0,  1])]
```

In [25]:
degree = 7
configurations = [
    [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  1],
    [-1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  1],
    [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,
         0,  1]
]

for row in configurations:
    support = [toIndex(i) for i, x in enumerate(row) if x == 1 or x == -1]
    basis = list(range(len(support)))
    P = pairing_matrix(degree, basis, support)
    print(f"Pairing matrix (support={support}, basis={basis}) has determinant: {np.linalg.det(P)}")

Pairing matrix (support=[(0, 0), (3, 1), (1, 5), (0, 7), (7, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (1, 1), (3, 3), (0, 7), (7, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0
Pairing matrix (support=[(0, 0), (1, 3), (5, 1), (0, 7), (7, 0)], basis=[0, 1, 2, 3, 4]) has determinant: 0.0


**Conclusion:** By the intervertibility criterion only the initial configuration $\mathbf 0 \in \mathbb Z^{V_d}$ can live in the support given above. Thus, no outcome of degree $7$ with support size $4$ exist.